# Generated by Django 3.2.2 on 2021-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='media/event_img/default.jpg', upload_to='event_img'),
        ),
    ]
