# Generated by Django 3.2.2 on 2021-06-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_events_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
