# Generated by Django 3.2.2 on 2021-06-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210625_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='event_img/default.jpg', upload_to='event_img'),
        ),
    ]
