# Generated by Django 3.2.2 on 2021-06-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='event_img/default.jpg', upload_to='vivaan_img')),
                ('pdf', models.FileField(blank=True, upload_to='vivaan_pdf')),
            ],
        ),
    ]
