# Generated by Django 3.2.2 on 2021-06-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vivaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='content',
        ),
    ]
