# Generated by Django 3.2.2 on 2021-06-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vivaan', '0002_remove_magazine_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazine',
            new_name='Mags',
        ),
    ]
