# Generated by Django 3.2.2 on 2021-06-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='event_img/default.jpg', upload_to='event_img'),
        ),
    ]
